version: "3.4"

services:
  mtasa-server:
    container_name: mta-tr
    image: "notfound/mtasa-server:1.5.8-20668-v4"
    env_file: local.env
    restart: always
    ports:
      - "22003:22003/udp"
      - "22126:22126/udp"
      - "22005:22005"
    volumes:
      - "./mta-resources:/resources"
      - "./config/acl.local.xml:/data/acl.xml"
      - "./config/mtaserver.local.conf:/data/mtaserver.local.conf"
      - "./native-modules/ml_sysutils.so:/native-modules/ml_sysutils.so"
      - "./volumes/data/:/data"
      - ./volumes/dynamic-files:/dynamic-files
    tty: true
    stdin_open: true

  mtatr-discord-bot:
    container_name: "mtatr-discord-bot"
    restart: always
    env_file: local.env
    build:
      context: ./mtatr-bot
      dockerfile: DiscordBot.DockerFile
    ports:
      - "8101:8101"

  mtatr-github-refresher:
    container_name: "mtatr-github-refresher"
    env_file: local.env
    restart: always
    build:
      context: ./www/mtatr-github-refresher
      dockerfile: DockerFile
    ports:
      - "8201:8201"

networks:
  default:
    name: mtatr-network
